### ISSUE TITLE
ViewlessStateProvider export missing

### ISSUE THREAD

**Issue by emmapejko** [ZacharyBohn/state-view-pattern#26]
I wanted to use the `ViewlessStateProvider` but it looks like the export is missing from `lib/state_view.dart`

![Screenshot 2023-09-26 at 3 00 12 PM](https://github.com/ZacharyBohn/state-view-pattern/assets/36683874/33fb54cd-f73d-4c38-a29b-1dae6da56649)

Thanks!!
Miss you hope the fam is good!

**Comment by ZacharyBohn** [comment]
Ah, good catch! I'll update that!

**Comment by ZacharyBohn** [comment]
This is resolved with #27. Update to v0.1.2 in order to get the fix.

Family is doing great! I miss you guys at AG; think about you a lot!
